### ISSUE TITLE
Issues with popup-bridge-ios - Checkout.js - new checkout SDK

### ISSUE THREAD

**Issue by IbrahimalKhayat** [paypal/paypal-checkout-components#1293]
### Description
Due to some business and technical restrictions I am trying to integrate a hybrid paypal solution into a native iOS app. I am faced sadly with some blockers while using the old and the new sdk.

I am using [Popupbridge-iOS](https://github.com/braintree/popup-bridge-ios) to handle the popup for better UX in addition to some javascript injection to trigger the button manually. 

[Popupbridge-iOS](https://github.com/braintree/popup-bridge-ios) is opening the popup in `SFSafariViewController` which might be why the following issues are being observed.

#### Part I: new checkout SDK v5.0.117 ([https://www.paypal.com/sdk/js](https://www.paypal.com/sdk/js))
Integrating [Popupbridge-iOS](https://github.com/braintree/popup-bridge-ios) seams to break new SDK v5.0.117 completely. 

Paypal login opens, however when the user clicks the approve button no callbacks are received and the page reloads creating and endless loop of clicking approve and reloading.

sample used code:
```
paypal.Buttons({
    createOrder: (data, actions) => {
        return paypalOrderId
    },
    onCancel: () => {
        console.log("onCancel");
        onCancel();
    },
    onError: err => {
        console.log("onError");
        onError(err);
    },
}).render('#paypal-button-container');
```

Note:
Added onApprove doesn't have an effect on the behaviour. Removing Popupbridge-iOS solves the issue. (horrible mobile UX though)

#### Part II: old checkout SDK v4.0.312 ([https://www.paypalobjects.com/api/checkout.js](https://www.paypalobjects.com/api/checkout.js))

Integrating [Popupbridge-iOS](https://github.com/braintree/popup-bridge-ios) to SDK v4.0.312 breaks functionalities in `actions.payment` and `actions.order` in the `onAuthorize` callback (this function get's called on approve). Error returned (misleading) `Client side order capture is only available for REST based transactions`. The error is happening since `orderID` is missing from the returned `data`

code sample:
```
paypal.Button.render({
    env: env,
    client: {
        sandbox: sandboxToken,
        production: prodToken
    },
    commit: true,
    payment: (data, actions) => {
        return paypalOrderId
    },
    onAuthorize: function (data, actions) {
        console.log(data) // {paymentToken: "2NK80999MU912601C", payerID: "MCN5HBD2TL6RU", intent: "authorize", button_version: "2.1.93"}
        return actions.order.authorize()
    },
    onCancel: () => onCancel,
    onError: err => onError
}, '#paypal-button-container');
```

on removing the integration of [Popupbridge-iOS](https://github.com/braintree/popup-bridge-ios) `orderID` is observed in the `data`.

I would like to know how to proceed and get some feedback regarding the issues mentioned.

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [x] Web View / Safari ViewController
- [ ] Other

**Comment by IbrahimalKhayat** [comment]
An update:

In v5, the popupBridge redirect_uri seams to be ignored and replaced with the return_url form GraphQL which is empty in our case and causes the flow to restart. Setting the url to an app link that matches the bridge expected url breaks the create payment order call.

The Checkout sdk source code seams to have a native redirect support however, I have failed to find a public mention on how to trigger that from the create order parameters.

finally popup-bridge.js is only sending `{ restart: start }` `onApprove` which will make disable most of the actions that are available form the smart button.

There are luckily some work arounds and different flows to follow:
- using checoutnow link directly with a redirect to an https client (this can redirect back to the app if needed)
- using checkout.js with the popupbridge and an endpoint that authorises or captures. (old mobile native SDK flow)
- migrate to Braintree

As I don't believe PayPal would do anything about the issues mentioned above I will close the issue.

**Comment by bluepnume** [comment]
Hi @IbrahimalKhayat -- reopening this one as I'd like to help narrow down the issues you were seeing with v5.

> when the user clicks the approve button no callbacks are received and the page reloads creating and endless loop of clicking approve and reloading

Can you elaborate on this -- does the user actually return to the mobile app, or do they get stuck in the browser window?

**Comment by bluepnume** [comment]
FYI -- may have a fix that works for this issue: https://github.com/paypal/paypal-checkout-components/issues/1294

We can roll it out and see if it helps you too. Thanks.

**Comment by bluepnume** [comment]
Hi, we've pushed out the hopeful fix in v5. Can you let me know if it works for you? Thanks!

**Comment by IbrahimalKhayat** [comment]
@bluepnume I can confirm that the popupbridge works now.

I also get and `orderId` in the response. However, If I try to call `actions.order.authorize` in the `onApprove` I get the api error:
`FROM: POST /smart/api/order/1DB7775220688294W/authorize HTTP/1.1`
```
{
    "ack": "permission_denied",
    "message": "Insufficient privileges"
}
```

We aren't sure If this a bad configuration form our side or something else. We would like to get some insight form you on the issue.

**Comment by bluepnume** [comment]
Hi, yeah -- that's a known limitation of the popup bridge. For now I recommend running the authorize on your server side with full client/secret credentials, that will work:

https://developer.paypal.com/docs/checkout/reference/server-integration/authorize-transaction/

@abarco -- going to turn this issue over to you. We should consider running LSAT upgrade during checkout, to allow client side order calls to happen even for popup bridge. Perhaps we can combine that with your effort to migrate over to LSAT upgrade for all SPB integrations, even on web. Thanks!

**Comment by IbrahimalKhayat** [comment]
thanks!
